<?php
/**
 * Title: Header template.
 *
 * Description: Defines header content.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="ie ie6 lte9 lte8 lte7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 7]>
<html class="ie ie7 lte9 lte8 lte7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 lte9 lte8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9]>
<html class="ie ie9" <?php language_attributes(); ?>> 
<![endif]-->
<!--[if gt IE 9]>  <html <?php language_attributes(); ?>> <![endif]-->
<!--[if !IE]><!--> 
<html <?php language_attributes(); ?>>
<!--<![endif]-->
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<meta name="viewport" content="width=device-width" />
	
	<title><?php wp_title(''); ?></title>
	
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>" />
<style>#clickMenu{max-width:550px;}</style>

	<!-- IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="<?php echo get_template_directory_uri(); ?>/inc/js/html5.js" type="text/javascript"></script>
	<![endif]-->
	
	<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>

<div class="container">
	
<?php do_action('cyberchimps_before_wrapper'); ?>

<div id="wrapper" class="container-fluid">	
	
<header id="cc-header" class="row-fluid">

<div id="header1">

<div id="raw1">

<div class="text1"><p>US DOT# 1846942<p></div>

<div class="text2">

<div class="text20"><p>Call For A Free Quote!</p></div>

<div class="text21"><p>207-344-5924</p></div>

</div>

</div>

<div id="raw1">

<div class="img1"><href="http://www.libertybellfurniture.com"><img src="http://www.libertybellfurniture.com/wp-content/uploads/2013/06/Liberty-Bell-Furniture21.png" /></a></div>

<div class="blockr"><img src="http://www.libertybellfurniture.com/wp-content/themes/response/images/kfink.jpg" style="margin-right:10px" /><a href="http://www.bbb.org/boston/business-reviews/movers/liberty-bell-moving-storage-in-portland-me-116146/" target="_blank"><img src="http://www.libertybellfurniture.com/wp-content/themes/response/images/bbbl.jpg" /></a></div>

</div>

<div id="raw1" style="padding:10px 0;">

<div class="socialb"><a href="http://www.facebook.com/libertybellfurniture" target="_blank"><img src="http://www.libertybellfurniture.com/wp-content/themes/response/images/facebook.png" class="simg" /></a><a href="https://plus.google.com/110374153308989437191/about" target="_blank"><img src="http://www.libertybellfurniture.com/wp-content/themes/response/images/gplus.png" class="simg" /></a><a href="http://www.linkedin.com/pub/kevin-finkenaur-at-liberty-bell-moving/19/154/498" target="_blank"><img src="http://www.libertybellfurniture.com/wp-content/themes/response/images/linkedin.png" class="simg" /></a><a href="http://www.youtube.com/user/LibertyBellMoving" target="_blank"><img src="http://www.libertybellfurniture.com/wp-content/themes/response/images/youtube.png" class="simg" /> </a></div>

<div class="rtext"><href="mailto:furnitureservice@libertybellmoving.com"><p>furnitureservice@libertybellmoving.com</a><p>Kevin Finkenaur</p><p>(207) 344-5924</p></div>

</div>


<ul id="clickMenu">
	<li><a href="http://www.libertybellfurniture.com/" tabindex="1">Home</a></li>
	<li><a href="http://www.libertybellfurniture.com/furniture-refinishing/" tabindex="1">Refinishing</a></li>
	<li><a href="http://www.libertybellfurniture.com/furniture-reupholstery/" tabindex="1">Reupholstery</a></li>
	<li><a href="http://www.libertybellfurniture.com/leather-refinishing/" tabindex="1">Leather</a></li>
	<li><a class="drop" href="#" tabindex="1">Commercial Accounts</a>
		<ul>
			<li><a href="http://www.libertybellfurniture.com/commercial-accounts#retailers">Retailers</a></li>
			<li><a href="http://www.libertybellfurniture.com/commercial-accounts#manufacturer">Manufacturers</a></li>
			<li><a href="http://www.libertybellfurniture.com/commercial-accounts#restaurants">Restaurants</a></li>
			<li><a href="http://www.libertybellfurniture.com/commercial-accounts#office">Business Offices</a></li>
			<li><a href="http://www.libertybellfurniture.com/commercial-accounts#moving">Moving Companies</a></li>
		</ul>
	</li>	
	<li><a href="http://www.libertybellfurniture.com/motels/" tabindex="1">Hotels & Inns</a></li>
<li><a class="drop" href="#" tabindex="1">More</a>		
<ul style="margin: 0 0 0 -31px;">
<li><a href="http://www.libertybellfurniture.com/furniture-repair-photo-gallery/" tabindex="1">Gallery</a></li>
<li><a href="http://www.libertybellfurniture.com/services-offered/" tabindex="1">Services</a></li>
<li><a href="http://www.libertybellfurniture.com/contact-us-today/" tabindex="1">Contact</a></li>
</ul>
</li>
</ul>

</header>
	
	<?php do_action('cyberchimps_before_navigation'); ?>

	<nav id="navigation" class="row-fluid" role="navigation">
      <div class="main-navigation navbar">
        <div class="navbar-center">
        	<div class="container">
          <?php /* hide collapsing menu if not responsive */
						if( cyberchimps_get_option( 'responsive_design', 'checked' ) ): ?>
  					<div class="nav-collapse collapse">
            <?php endif; ?>
          		<?php wp_nav_menu( array( 'theme_location'  => 'primary', 'menu_class' => 'nav', 'walker' => new cyberchimps_walker(), 'fallback_cb' => 'cyberchimps_fallback_menu' ) ); ?>
			
			<?php if( cyberchimps_get_option( 'searchbar', 1 ) == "1" ) : ?>
				<div class="menu-searchbar">
					<?php get_search_form(); ?>
				</div>
      <?php endif; ?>
      <?php /* hide collapsing menu if not responsive */
						if( cyberchimps_get_option( 'responsive_design', 'checked' ) ): ?>
			</div><!-- collapse -->
			
            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
      <?php endif; ?>
          </div><!-- container -->
        </div><!-- .navbar-inner .row-fluid -->
      </div><!-- main-navigation navbar -->
	</nav><!-- #navigation -->
	
	<?php do_action('cyberchimps_after_navigation'); ?>