<?php
/**
 * Created by IntelliJ IDEA.
 * User: luzaponte
 * Date: 10/25/13
 * Time: 6:15 PM
 * To change this template use File | Settings | File Templates.
 */

class Reviews
{

	public $name;

	public function __construct()
	{

		$this->name = 'mdpLocalBusinessInfo';

		register_activation_hook(__FILE__ , array($this , 'mdp_activate'));
		register_deactivation_hook(__FILE__ , array($this , 'mdp_deactivate'));
		register_uninstall_hook(__FILE__ , array($this , 'mdp_uninstall'));

	}

	private function getAuthor()
	{

		$first = array(
			'JOHN' ,
			'JAMES' ,
			'MICHAEL' ,
			'DAVID' ,
			'EMILY' ,
			'ELIZABETH' ,
			'WILLIAM' ,
			'DANIEL' ,
			'ANDREW' ,
			'SARAH' ,
			'THOMAS' ,
			'EMMA' ,
			'ROBERT' ,
			'RYAN' ,
			'JESSICA' ,
			'MATTHEW' ,
			'JACOB' ,
			'JACK' ,
			'ALEXANDER' ,
			'JOSEPH' ,
			'MARY' ,
			'JOSHUA' ,
			'JENNIFER' ,
			'MARK' ,
			'GRACE' ,
			'ANNA' ,
			'HANNAH' ,
			'NICOLE' ,
			'CHRISTOPHER' ,
			'PAUL' ,
			'OLIVIA' ,
			'ANTHONY' ,
			'ASHLEY' ,
			'NOAH' ,
			'SAMUEL' ,
			'MARIE' ,
			'MICHELLE' ,
			'BENJAMIN' ,
			'MARIA' ,
			'RICHARD' ,
			'SAMANTHA' ,
			'ADAM' ,
			'JORDAN' ,
			'CHLOE' ,
			'ETHAN' ,
			'RACHEL' ,
			'LAUREN' ,
			'BRIAN' ,
			'JASON' ,
			'JONATHAN' ,
			'AVA' ,
			'LIAM' ,
			'ALEX' ,
			'KEVIN' ,
			'CHARLOTTE' ,
			'TYLER' ,
			'AMANDA' ,
			'ROSE' ,
			'PETER' ,
			'GEORGE' ,
			'LUKE' ,
			'REBECCA' ,
			'SOPHIA' ,
			'CHARLES' ,
			'JUSTIN' ,
			'MORGAN' ,
			'VICTORIA' ,
			'ELLA' ,
			'MEGAN' ,
			'MORGAN' ,
			'AMY' ,
			'AARON' ,
			'LOGAN' ,
			'BRANDON' ,
			'EDWARD' ,
			'NICHOLAS' ,
			'NATHAN' ,
			'KELLY' ,
			'STEPHANIE' ,
			'STEVEN' ,
			'ABIGAIL' ,
			'OLIVER' ,
			'GABRIEL' ,
			'LAURA' ,
			'CLAIRE' ,
			'PATRICK' ,
			'TAYLOR' ,
			'LEE' ,
			'ANDR├ëA' ,
			'HENRY' ,
			'KYLE' ,
			'ALICE' ,
			'ANDREA' ,
			'ANNE' ,
			'KAYLA' ,
			'NATALIE' ,
			'JULIA' ,
			'AMELIA' ,
			'SAM' ,
			'DYLAN' ,
			'ALEXIS' ,
			'ANN' ,
			'LILY' ,
			'IAN' ,
			'KAREN' ,
			'SAM' ,
			'ERIC' ,
			'KAREN' ,
			'KATHERINE' ,
			'LISA' ,
			'MADISON' ,
			'STEPHEN' ,
			'JANE' ,
			'CONNOR' ,
			'OWEN' ,
			'MIA' ,
			'LUCAS' ,
			'ISABELLA' ,
			'SCOTT' ,
			'AUSTIN' ,
			'CAMERON' ,
			'SETH' ,
			'ELIJAH' ,
			'MELISSA' ,
			'LUCY' ,
			'SIMON' ,
			'TIMOTHY' ,
			'ZOE' ,
			'ERIN' ,
			'JEAN' ,
			'ALEXANDRA' ,
			'MAYA' ,
			'ALYSSA' ,
			'JEAN' ,
			'LOUISE' ,
			'CATHERINE' ,
			'JESUS' ,
			'SOPHIE' ,
			'DANIELLE' ,
			'SEAN' ,
			'JOS├ë' ,
			'SEBASTIAN' ,
			'CALEB' ,
			'MOLLY' ,
			'NINA' ,
			'ADRIAN' ,
			'HARRY' ,
			'MAX' ,
			'RILEY' ,
			'ELI' ,
			'NAOMI' ,
			'EVELYN' ,
			'LYNN' ,
			'MASON' ,
			'ZACHARY' ,
			'ELI' ,
			'AVERY' ,
			'BEN' ,
			'EVAN' ,
			'CHRISTIAN' ,
			'ISAAC' ,
			'CAROLINE' ,
			'LOUIS' ,
			'ALAN' ,
			'JEREMY' ,
			'KATIE' ,
			'LEAH' ,
			'SARA' ,
			'RUTH' ,
			'JAMIE' ,
			'LYDIA' ,
			'AMBER' ,
			'VINCENT' ,
			'JENNA' ,
			'JULIE' ,
			'AIDEN' ,
			'COURTNEY' ,
			'PAIGE' ,
			'JAKE' ,
			'DIANA' ,
			'LEVI' ,
			'MARTIN' ,
			'SUSAN' ,
			'JACKSON' ,
			'JULIAN' ,
			'JADE' ,
			'KENNETH' ,
			'HELEN' ,
			'JOEL' ,
			'VANESSA' ,
			'JASMINE' ,
			'KIMBERLY' ,
			'MARGARET' ,
			'SYDNEY' ,
			'CHRIS' ,
			'KATE' ,
			'ANGELA' ,
			'JESSE' ,
			'KAI' ,
			'KIM' ,
			'TIFFANY' ,
			'XAVIER' ,
			'EZRA' ,
			'KIM' ,
			'TOM' ,
			'ARTHUR' ,
			'HEATHER' ,
			'TOM' ,
			'BROOKE' ,
			'ELEANOR' ,
			'LEO' ,
			'SHANNON' ,
			'BLAKE' ,
			'CHRISTINA' ,
			'HUNTER' ,
			'CHARLIE' ,
			'CHRISTINE' ,
			'JAY' ,
			'AUDREY' ,
			'COLIN' ,
			'ELENA' ,
			'GREGORY' ,
			'JOSH' ,
			'EVA' ,
			'NATASHA' ,
			'OSCAR' ,
			'RENEE' ,
			'SOFIA' ,
			'CODY' ,
			'FRANK' ,
			'NATHANIEL' ,
			'ARIA' ,
			'DEAN' ,
			'ELLEN' ,
			'ALLISON' ,
			'CARLOS' ,
			'GAVIN' ,
			'TARA' ,
			'CLAUDIA' ,
			'HOLLY' ,
			'RUBY' ,
			'ISABELLE' ,
			'PATRICIA' ,
			'VERONICA' ,
			'FRANCIS' ,
			'MONICA' ,
			'SANDRA' ,
			'SHANE' ,
			'TRISTAN' ,
			'ALICIA' ,
			'DANA' ,
			'ROBIN' ,
			'FELIX' ,
			'BELLA' ,
			'BRITTANY' ,
			'CARTER' ,
			'LINDA' ,
			'MARCUS' ,
			'QUINN' ,
			'ANGEL' ,
			'BOB' ,
			'ESTHER' ,
			'JUDE' ,
			'BRIANNA' ,
			'ELLIE' ,
			'JEFFREY' ,
			'JARED' ,
			'MELANIE' ,
			'SASHA' ,
			'ARIEL' ,
			'FINN' ,
			'SPENCER' ,
			'CAROL' ,
			'CASSANDRA' ,
			'COLE' ,
			'DOUGLAS' ,
			'KEITH' ,
			'LUIS' ,
			'WYATT' ,
			'AIDAN' ,
			'CAROL' ,
			'CHELSEA' ,
			'MACKENZIE' ,
			'MIRANDA' ,
			'SILAS' ,
			'STEVE' ,
			'VICTOR' ,
			'ELISE' ,
			'HARPER' ,
			'JOSEPHINE' ,
			'MADELINE' ,
			'ASHER' ,
			'CAITLIN' ,
			'DAWN' ,
			'JOE' ,
			'NADIA' ,
			'FIONA' ,
			'LUCA' ,
			'CHASE' ,
			'HAYDEN'
		);

		$last = array(
			'SMITH',
			'JOHNSON',
			'WILLIAMS',
			'JONES',
			'BROWN',
			'DAVIS',
			'MILLER',
			'WILSON',
			'MOORE',
			'TAYLOR',
			'ANDERSON',
			'THOMAS',
			'JACKSON',
			'WHITE',
			'HARRIS',
			'MARTIN',
			'THOMPSON',
			'GARCIA',
			'MARTINEZ',
			'ROBINSON'
		              );

		$first_num = rand(0, (count($first)- 1));
		$last_num = rand(0, (count($last)- 1));
		return $first[$first_num].' '.$last[$last_num];

	}

	private function getProvider()
	{
		$array = array(
			'website design::http://website-design.sidcreations.com::Sid Creations an seo, website design and website hosting company develops the latest html5, seo and mobile technology websites.',
			'seo company::http://seo-company.sidcreations.com::Sid Creations is an seo company that specializes in the latest technology utilizing seo algorithms for seo services and website design.',
			'sell house quickly::http://propertiescentralhomebuyers.com::We help you sell your house quickly. From divorce, inheritance, foreclosure, burdensome rental property, we buy houses in any condition or situation.',
			'san francisco plumber::http://24-7rooter.com::San Francisco plumber provides plumbing services. We are licensed and highly trained plumbing professionals that are fast and efficient.',
			'we buy houses::http://propertiescentralhomebuyers.com::We help you sell your house quickly. From divorce, inheritance, foreclosure, burdensome rental property, we buy houses in any condition or situation.',
			'mlg::http://mlglive.com::MLG Live has Free clan websites for XBOX Clans, the only one combining Xbox Live Gamertag info and youtube videos.',
			'nike rsvp::http://rsvphead.com::The best Nike RSVP service available and the only free Nike RSVP out there.',
			'fitness equipment::http://fitnessbrokersusa.com::A list of treadmills, elliptical, bikes, and strength equipment sold by Fitness Brokers USA, the leading seller of new, used and reconditioned fitness equipment.',
			'exercise bikes::http://fitnessbrokersusa.com/fitness-equipment/indoor-cycling-bikes.html::A list of fitness equipment indoor cycling bikes from Fitness Brokers USA, the leading seller of new, used and reconditioned fitness equipment.',
			'elliptical::http://fitnessbrokersusa.com/fitness-equipment/elliptical-training.html::A list of fitness equipment elliptical training from Fitness Brokers USA, the leading seller of new, used and reconditioned fitness equipment.',
			'treadmills::http://fitnessbrokersusa.com/fitness-equipment/treadmills.html::A list of fitness equipment treadmills from Fitness Brokers USA, the leading seller of new, used and reconditioned fitness equipment.'

		);
		$num = rand(0, (count($array)- 1));
		return $array[$num];
	}



	private function getReviewBody()
	{
		$adj = array(
			'Amazing',
			'Awesome',
			'Blithesome',
			'Excellent',
			'Fabulous',
			'Fantastic',
			'Favorable',
			'Fortuitous',
			'Great',
			'Incredible',
			'Ineffable',
			'Mirthful',
			'Outstanding',
			'Perfect',
			'Propitious',
			'Remarkable',
			'Smart',
			'Spectacular',
			'Splendid',
			'Stellar',
			'Stupendous',
			'Super',
			'Ultimate',
			'Unbelievable',
			'Wondrous'
		);
		$adj_num =  rand(0, (count($adj)- 1));
		$array = array(
			'This is a '.$adj[$adj_num].' company. They provide great [keyword].',
			'No complaints with [keyword]. I have done business with them for years.',
			$adj[$adj_num].' [keyword] business with great customer service.',
			'This website is '.$adj[$adj_num].' they have the best [keyword].',
			$adj[$adj_num].' [keyword]. Thank you again.',
			'Five stars in my book. I will be back for more '.$adj[$adj_num].' [keyword]'
		);

		$num = rand(0, (count($array)- 1));
		return $array[$num];
	}


	public function buildReview()
	{
		return ucwords(strtolower(self::getAuthor()))."::".self::getReviewBody()."::".self::getProvider();

	}

}