<?php
    $this->business_list[]=array('level'=>'level0','name'=>'LocalBusiness','label'=>__('Local Business', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'AnimalShelter','label'=>__('Animal Shelter', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'AutomotiveBusiness','label'=>__('Automotive Business', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoBodyShop','label'=>__('Auto Body Shop', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoDealer','label'=>__('Auto Dealer', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoPartsStore','label'=>__('Auto Parts Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoRental','label'=>__('Auto Rental', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoRepair','label'=>__('Auto Repair', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoWash','label'=>__('Auto Wash', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'GasStation','label'=>__('Gas Station', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MotorcycleDealer','label'=>__('Motorcycle Dealer', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MotorcycleRepair','label'=>__('Motorcycle Repair', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'ChildCare','label'=>__('Child Care', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'DryCleaningOrLaundry','label'=>__('Dry Cleaning Or Laundry', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'EmergencyService','label'=>__('Emergency Service', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'FireStation','label'=>__('Fire Station', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Hospital','label'=>__('Hospital', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'PoliceStation','label'=>__('Police Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'EmploymentAgency','label'=>__('Employment Agency', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'EntertainmentBusiness','label'=>__('Entertainment Business', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AdultEntertainment','label'=>__('Adult Entertainment', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AmusementPark','label'=>__('Amusement Park', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ArtGallery','label'=>__('Art Gallery', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Casino','label'=>__('Casino', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ComedyClub','label'=>__('Comedy Club', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MovieTheater','label'=>__('Movie Theater', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'NightClub','label'=>__('Night Club', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'FinancialService','label'=>__('Financial Service', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AccountingService','label'=>__('Accounting Service', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutomatedTeller','label'=>__('Automated Teller', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BankOrCreditUnion','label'=>__('Bank Or Credit Union', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'InsuranceAgency','label'=>__('Insurance Agency', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'FoodEstablishment','label'=>__('Food Establishment', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Bakery','label'=>__('Bakery', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BarOrPub','label'=>__('Bar Or Pub', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Brewery','label'=>__('Brewery', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'CafeOrCoffeeShop','label'=>__('Cafe Or Coffee Shop', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'FastFoodRestaurant','label'=>__('Fast Food Restaurant', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'IceCreamShop','label'=>__('Ice Cream Shop', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Restaurant','label'=>__('Restaurant', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Winery','label'=>__('Winery', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'GovernmentOffice','label'=>__('Government Office', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'PostOffice','label'=>__('Post Office', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'HealthAndBeautyBusiness','label'=>__('Health And Beauty Business', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BeautySalon','label'=>__('Beauty Salon', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'DaySpa','label'=>__('Day Spa', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HairSalon','label'=>__('Hair Salon', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HealthClub','label'=>__('Health Club', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'NailSalon','label'=>__('Nail Salon', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'TattooParlor','label'=>__('Tattoo Parlor', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'HomeAndConstructionBusiness','label'=>__('Home And Construction Business', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Electrician','label'=>__('Electrician', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'GeneralContractor','label'=>__('General Contractor', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HVACBusiness','label'=>__('HVAC Business', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HousePainter','label'=>__('House Painter', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Locksmith','label'=>__('Locksmith', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MovingCompany','label'=>__('Moving Company', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Plumber','label'=>__('Plumber', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'RoofingContractor','label'=>__('Roofing Contractor', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'InternetCafe','label'=>__('Internet Cafe', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Library','label'=>__('Library', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'LodgingBusiness','label'=>__('Lodging Business', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BedAndBreakfast','label'=>__('Bed And Breakfast', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Hostel','label'=>__('Hostel', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Hotel','label'=>__('Hotel', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Motel','label'=>__('Motel', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'MedicalOrganization','label'=>__('Medical Organization', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Dentist','label'=>__('Dentist', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'DiagnosticLab','label'=>__('Diagnostic Lab', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Hospital','label'=>__('Hospital', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MedicalClinic','label'=>__('Medical Clinic', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Optician','label'=>__('Optician', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Pharmacy','label'=>__('Pharmacy', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Physician','label'=>__('Physician', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'VeterinaryCare','label'=>__('Veterinary Care', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'ProfessionalService','label'=>__('Professional Service', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AccountingService','label'=>__('Accounting Service', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Attorney','label'=>__('Attorney', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Dentist','label'=>__('Dentist', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Electrician','label'=>__('Electrician', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'GeneralContractor','label'=>__('General Contractor', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HousePainter','label'=>__('House Painter', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Locksmith','label'=>__('Locksmith', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Notary','label'=>__('Notary', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Plumber','label'=>__('Plumber', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'RoofingContractor','label'=>__('Roofing Contractor', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'RadioStation','label'=>__('Radio Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'RealEstateAgent','label'=>__('Real Estate Agent', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'RecyclingCenter','label'=>__('Recycling Center', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'SelfStorage','label'=>__('Self Storage', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'ShoppingCenter','label'=>__('Shopping Center', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'SportsActivityLocation','label'=>__('Sports Activity Location', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BowlingAlley','label'=>__('Bowling Alley', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ExerciseGym','label'=>__('Exercise Gym', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'GolfCourse','label'=>__('Golf Course', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HealthClub','label'=>__('Health Club', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'PublicSwimmingPool','label'=>__('Public Swimming Pool', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'SkiResort','label'=>__('Ski Resort', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'SportsClub','label'=>__('Sports Club', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'StadiumOrArena','label'=>__('Stadium Or Arena', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'TennisComplex','label'=>__('Tennis Complex', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Store','label'=>__('Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'AutoPartsStore','label'=>__('Auto Parts Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BikeStore','label'=>__('Bike Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BookStore','label'=>__('Book Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ClothingStore','label'=>__('Clothing Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ComputerStore','label'=>__('Computer Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ConvenienceStore','label'=>__('Convenience Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'DepartmentStore','label'=>__('Department Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ElectronicsStore','label'=>__('Electronics Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Florist','label'=>__('Florist', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'FurnitureStore','label'=>__('Furniture Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'GardenStore','label'=>__('Garden Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'GroceryStore','label'=>__('Grocery Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HardwareStore','label'=>__('Hardware Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HobbyShop','label'=>__('Hobby Shop', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HomeGoodsStore','label'=>__('Home Goods Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'JewelryStore','label'=>__('Jewelry Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'LiquorStore','label'=>__('Liquor Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MensClothingStore','label'=>__('Mens Clothing Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MobilePhoneStore','label'=>__('Mobile Phone Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MovieRentalStore','label'=>__('Movie Rental Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'MusicStore','label'=>__('Music Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'OfficeEquipmentStore','label'=>__('Office Equipment Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'OutletStore','label'=>__('Outlet Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'PawnShop','label'=>__('Pawn Shop', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'PetStore','label'=>__('Pet Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ShoeStore','label'=>__('Shoe Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'SportingGoodsStore','label'=>__('Sporting Goods Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'TireShop','label'=>__('Tire Shop', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'ToyStore','label'=>__('Toy Store', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'WholesaleStore','label'=>__('Wholesale Store', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'TelevisionStation','label'=>__('Television Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'TouristInformationCenter','label'=>__('Tourist Information Center', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'TravelAgency','label'=>__('Travel Agency', 'wp_localseo'));
$this->business_list[]=array('level'=>'level0','name'=>'CivicStructure','label'=>__('Civic Structure', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Airport','label'=>__('Airport', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Aquarium','label'=>__('Aquarium', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Beach','label'=>__('Beach', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'BusStation','label'=>__('Bus Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'BusStop','label'=>__('Bus Stop', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Campground','label'=>__('Campground', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Cemetery','label'=>__('Cemetery', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Crematorium','label'=>__('Crematorium', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'EventVenue','label'=>__('Event Venue', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'FireStation','label'=>__('Fire Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'GovernmentBuilding','label'=>__('Government Building', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'CityHall','label'=>__('City Hall', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Courthouse','label'=>__('Courthouse', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'DefenceEstablishment','label'=>__('Defence Establishment', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Embassy','label'=>__('Embassy', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'LegislativeBuilding','label'=>__('Legislative Building', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Hospital','label'=>__('Hospital', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'MovieTheater','label'=>__('Movie Theater', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Museum','label'=>__('Museum', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'MusicVenue','label'=>__('Music Venue', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Park','label'=>__('Park', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'ParkingFacility','label'=>__('Parking Facility', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'PerformingArtsTheater','label'=>__('Performing Arts Theater', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'PlaceOfWorship','label'=>__('Place Of Worship', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'BuddhistTemple','label'=>__('Buddhist Temple', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'CatholicChurch','label'=>__('Catholic Church', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Church','label'=>__('Church', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'HinduTemple','label'=>__('Hindu Temple', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Mosque','label'=>__('Mosque', 'wp_localseo'));
        $this->business_list[]=array('level'=>'level2','name'=>'Synagogue','label'=>__('Synagogue', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Playground','label'=>__('Playground', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'PoliceStation','label'=>__('Police Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'RVPark','label'=>__('RV Park', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'StadiumOrArena','label'=>__('Stadium Or Arena', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'SubwayStation','label'=>__('Subway Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'TaxiStand','label'=>__('Taxi Stand', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'TrainStation','label'=>__('Train Station', 'wp_localseo'));
    $this->business_list[]=array('level'=>'level1','name'=>'Zoo','label'=>__('Zoo', 'wp_localseo'));    
?>